# Generated by Django 5.0 on 2024-01-24 13:50

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CourseContent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Course_name', models.CharField(max_length=100)),
                ('Course_students', models.CharField(max_length=100)),
                ('Course_image', models.ImageField(default=0, upload_to='')),
                ('Course_price', models.CharField(max_length=100)),
                ('Course_rating', models.CharField(max_length=100)),
                ('Course_time', models.CharField(max_length=100)),
            ],
        ),
    ]
