# Generated by Django 5.0 on 2024-01-29 10:24

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapi', '0004_inquerry'),
    ]

    operations = [
        migrations.CreateModel(
            name='OverView',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Course_overview', models.CharField(max_length=1000)),
                ('Course_use', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Review', to='myapi.particularcourse')),
            ],
        ),
    ]
