# Generated by Django 5.0 on 2024-01-31 05:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapi', '0005_overview'),
    ]

    operations = [
        migrations.RenameField(
            model_name='overview',
            old_name='Course_use',
            new_name='Course_r',
        ),
    ]
