# Generated by Django 5.0 on 2024-02-08 12:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapi', '0007_register'),
    ]

    operations = [
        migrations.AddField(
            model_name='overview',
            name='Course_QA',
            field=models.CharField(default=1, max_length=100),
            preserve_default=False,
        ),
    ]
