# Generated by Django 5.0 on 2024-02-08 12:55

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapi', '0008_overview_course_qa'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='overview',
            name='Course_QA',
        ),
        migrations.CreateModel(
            name='Demo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Course_QA', models.CharField(max_length=100)),
                ('Course_r', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Demo', to='myapi.particularcourse')),
            ],
        ),
    ]
