# Generated by Django 5.0 on 2024-02-10 12:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapi', '0009_remove_overview_course_qa_demo'),
    ]

    operations = [
        migrations.AddField(
            model_name='register',
            name='otp',
            field=models.CharField(default=1, max_length=4),
            preserve_default=False,
        ),
    ]
