# Generated by Django 5.0 on 2024-02-10 13:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapi', '0010_register_otp'),
    ]

    operations = [
        migrations.AlterField(
            model_name='register',
            name='otp',
            field=models.IntegerField(default=1),
        ),
    ]
