# Generated by Django 5.0 on 2024-02-12 06:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapi', '0011_alter_register_otp'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='register',
            name='otp',
        ),
    ]
