# Generated by Django 5.0 on 2024-02-13 18:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapi', '0012_remove_register_otp'),
    ]

    operations = [
        migrations.AddField(
            model_name='register',
            name='otp',
            field=models.IntegerField(default=0),
        ),
    ]
