# Generated by Django 5.0 on 2024-02-14 10:49

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapi', '0013_register_otp'),
    ]

    operations = [
        migrations.CreateModel(
            name='Rating',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Course_ratername', models.CharField(max_length=51)),
                ('Course_rate', models.CharField(max_length=77)),
                ('Course_rateview', models.CharField(max_length=1999)),
                ('Course_rawrate', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rateview', to='myapi.particularcourse')),
            ],
        ),
    ]
