# Generated by Django 4.1.13 on 2024-02-27 12:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapi', '0015_alter_particularcourse_course_video'),
    ]

    operations = [
        migrations.AlterField(
            model_name='particularcourse',
            name='Course_video',
            field=models.CharField(max_length=300),
        ),
    ]
