# Generated by Django 4.1.13 on 2024-03-03 18:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapi', '0017_register_paid_register_purchased_course'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='register',
            name='Purchased_Course',
        ),
        migrations.AlterField(
            model_name='register',
            name='Paid',
            field=models.BooleanField(default=False),
        ),
    ]
