# Generated by Django 4.1.13 on 2024-03-04 05:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('myapi', '0018_remove_register_purchased_course_alter_register_paid'),
    ]

    operations = [
        migrations.CreateModel(
            name='Paid_Course_Content',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Course_Video_Mains', models.CharField(max_length=1000)),
                ('Purchased_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Holder', to='myapi.register')),
                ('Which_Course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Main', to='myapi.particularcourse')),
            ],
        ),
    ]
