# Generated by Django 4.1.13 on 2024-03-04 12:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapi', '0020_remove_paid_course_content_which_course'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='paid_course_content',
            name='Course_Video_Mains',
        ),
        migrations.RemoveField(
            model_name='paid_course_content',
            name='Purchased_by',
        ),
        migrations.AddField(
            model_name='paid_course_content',
            name='Select',
            field=models.CharField(choices=[('1', '1'), ('2', '2'), ('3', '3'), ('4', '4'), ('5', '5'), ('6', '6'), ('7', '7'), ('8', '8')], default='JAVA', max_length=20),
        ),
    ]
