# Generated by Django 4.1.13 on 2024-03-04 12:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('myapi', '0021_remove_paid_course_content_course_video_mains_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='paid_course_content',
            name='Paid_Course_video',
            field=models.CharField(default=1, max_length=200),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='paid_course_content',
            name='Selected_Student',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='Selected', to='myapi.register'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='paid_course_content',
            name='Select',
            field=models.CharField(choices=[('Java', 'Java'), ('Python', 'Python'), ('Dot_net', 'Dot_net'), ('Java_Script', 'Java_Script')], default=None, max_length=20),
        ),
    ]
