# Generated by Django 4.1.13 on 2024-03-04 12:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapi', '0022_paid_course_content_paid_course_video_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='paid_course_content',
            name='Selected_Student',
        ),
        migrations.AlterField(
            model_name='paid_course_content',
            name='Select',
            field=models.CharField(choices=[('Java', 'Java'), ('Python', 'Python'), ('Dot_net', 'Dot_net'), ('Java_Script', 'Java_Script')], max_length=20),
        ),
    ]
