# Generated by Django 4.1.13 on 2024-03-05 06:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapi', '0023_remove_paid_course_content_selected_student_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='register',
            name='Course_purchased',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
