# Generated by Django 4.1.13 on 2024-03-07 07:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapi', '0026_paid_course_content_selected_student'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='paid_course_content',
            name='Selected_Student',
        ),
    ]
