# Generated by Django 4.1.13 on 2024-03-18 10:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapi', '0027_remove_paid_course_content_selected_student'),
    ]

    operations = [
        migrations.AddField(
            model_name='coursecontent',
            name='Course_PName',
            field=models.CharField(default=1, max_length=100),
            preserve_default=False,
        ),
    ]
