# Generated by Django 4.1.13 on 2024-03-18 10:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapi', '0028_coursecontent_course_pname'),
    ]

    operations = [
        migrations.AlterField(
            model_name='paid_course_content',
            name='Select',
            field=models.CharField(choices=[('Java', 'Java'), ('Python', 'Python'), ('Dot_net', 'Dot_net'), ('Javascript', 'Javascript')], max_length=20),
        ),
    ]
